language: php
sudo: false

php:
 - 5.6

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c phpunit.conf --token=$SECRET_TOKEN --only=tests --test-run-id=11084

script:
  - phpunit --configuration config.xml --log-junit results.xml

after_script:
  - hiptest-publisher -c phpunit.conf --token=$SECRET_TOKEN --push=results.xml --test-run-id=11084
